[package]
name = "halo2-tuto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#halo2 = "^0.1"
halo2 = { path = "../halo2" }
